# Form implementation generated from reading ui file 'd:\InstaThread\ui\ui_files\loginForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ui import resource 



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Iconshortcut/IconShortcut.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("QWidget#widget {\n"
"    background-image:url(:/img/loginForm.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain; \n"
"}")
        self.widget.setObjectName("widget")
        self.username = QtWidgets.QLineEdit(parent=self.widget)
        self.username.setGeometry(QtCore.QRect(400, 297, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setItalic(True)
        self.username.setFont(font)
        self.username.setStyleSheet("background:transparent;\n"
"border:0;\n"
"color:white")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=self.widget)
        self.password.setGeometry(QtCore.QRect(400, 407, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setItalic(False)
        self.password.setFont(font)
        self.password.setStyleSheet("background:transparent;\n"
"border:0;\n"
"color:white")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.loginBtn = QtWidgets.QPushButton(parent=self.widget)
        self.loginBtn.setGeometry(QtCore.QRect(470, 490, 181, 51))
        self.loginBtn.setStyleSheet("background:transparent;\n"
"border:0;\n"
"")
        self.loginBtn.setText("")
        self.loginBtn.setObjectName("loginBtn")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(20, 570, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(470, 560, 311, 20))
        self.label_2.setStyleSheet("color:white")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.closeBtn = QtWidgets.QPushButton(parent=self.widget)
        self.closeBtn.setGeometry(QtCore.QRect(760, 20, 23, 23))
        self.closeBtn.setMinimumSize(QtCore.QSize(23, 23))
        self.closeBtn.setMaximumSize(QtCore.QSize(23, 23))
        self.closeBtn.setStyleSheet("background: transparent")
        self.closeBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconBtn/closeBtn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeBtn.setIcon(icon1)
        self.closeBtn.setObjectName("closeBtn")
        self.minimizeBtn = QtWidgets.QPushButton(parent=self.widget)
        self.minimizeBtn.setGeometry(QtCore.QRect(728, 20, 23, 23))
        self.minimizeBtn.setMinimumSize(QtCore.QSize(23, 23))
        self.minimizeBtn.setMaximumSize(QtCore.QSize(23, 23))
        self.minimizeBtn.setStyleSheet("background: transparent")
        self.minimizeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconBtn/minimizeBtn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeBtn.setIcon(icon2)
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.rememberLoginBtn = QtWidgets.QCheckBox(parent=self.widget)
        self.rememberLoginBtn.setGeometry(QtCore.QRect(390, 460, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setBold(False)
        font.setWeight(50)
        self.rememberLoginBtn.setFont(font)
        self.rememberLoginBtn.setStyleSheet("color: rgb(255, 255, 255)")
        self.rememberLoginBtn.setObjectName("rememberLoginBtn")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Instathread"))
        self.label.setText(_translate("MainWindow", "1.0.0.0"))
        self.label_2.setText(_translate("MainWindow", "Chờ đăng nhập"))
        self.rememberLoginBtn.setText(_translate("MainWindow", "Ghi nhớ"))
